export function buildStage1Prompt(topic: string): string {
  return [
    '你是一名资深前端技术作者和前端面试教练。',
    '请围绕下面给定的前端知识点，直接输出一份高质量的中文讲解草稿。',
    '不要向用户追问信息，不要解释你要做什么，直接开始写。',
    '草稿必须让前端工程师、面试候选人和喜欢收藏实用内容的读者都觉得有价值。',
    '优先讲清楚准确含义、运行机制、实现细节、边界情况、常见错误和高频面试陷阱。',
    '避免空话、套话、鸡汤、泛泛而谈和教科书式废话。',
    '必须严格使用下面这些标题：',
    '概念定义：',
    '为什么重要：',
    '核心机制：',
    '常见误区与考点：',
    '一句话总结：',
    '要求：',
    '- 标题必须保持上面的中文标题完全不变，标题下的内容必须全部使用简体中文。',
    '- 在“概念定义”中，讲清楚这个知识点到底是什么，并指出它最容易和什么概念混淆。',
    '- 在“为什么重要”中，讲清楚它在前端开发中的真实价值，例如性能、可维护性、调试难度、渲染行为、状态一致性、工程实践或面试价值。',
    '- 在“核心机制”中，讲清楚它是怎么工作的，开发时应注意什么，并至少补一个容易忽略的细节、边界情况或真实场景。',
    '- 在“常见误区与考点”中，写出常见误区、错误写法、面试高频考点，以及回答时应该抓住的重点。',
    '- 在“一句话总结”中，写一句简洁、有记忆点、值得收藏的总结。',
    '- 整体语气要专业、直接、像资深前端工程师在带新人，不要像营销文案。',
    '- 不要输出 JSON。',
    '- 不要输出 Markdown 代码块。',
    '- 不要输出 HTML。',
    '- 草稿长度要适中，后续可以稳定拆成 4 到 8 张纯文本卡片。',
    '',
    `知识点：${topic}`,
  ].join('\n');
}

export function buildStage1RetryPrompt(topic: string, previousDraft: string, validationError: string): string {
  return [
    '你上一次输出的草稿不合格，请立即重写。',
    '不要提问，不要索取更多上下文，只输出最终草稿。',
    '必须保持下面这些标题完全一致：',
    '概念定义：',
    '为什么重要：',
    '核心机制：',
    '常见误区与考点：',
    '一句话总结：',
    '每个标题下面的内容都必须使用简体中文。',
    '每一节都必须有具体、有用、能落地的内容。',
    '',
    `知识点：${topic}`,
    '',
    '校验错误：',
    validationError,
    '',
    '上一版草稿：',
    previousDraft,
  ].join('\n');
}

export function buildStage2Prompt(topic: string, stage1Draft: string): string {
  return [
    '请把下面这份讲解草稿，转换成一个严格合法的 JSON 对象，用于生成值得收藏的前端知识卡片。',
    '只输出 JSON 对象本身，不要解释，不要 Markdown，不要代码块。',
    'JSON 中所有给用户看的内容都必须使用简体中文。',
    '内容必须严格围绕请求的知识点，不允许偷换成别的概念。',
    '内容质量要求：',
    '- 每一张卡片都要有实用信息，不能像口号或空洞摘要。',
    '- 必须讲清楚概念本身，并保持前端工程语境下的准确性。',
    '- 要突出实现细节、运行表现、边界情况和常见坑。',
    '- 至少有一张 bullet 类型卡片专门写高频面试陷阱、易混点或常见考点。',
    '- 至少有一张 bullet 类型卡片要写工程实践里真正该注意的点。',
    '- 让读者觉得值得收藏，但靠内容密度，不靠营销语气。',
    '结构要求：',
    '- 根对象必须包含英文键名：topic、styleVersion、cards',
    '- styleVersion 的值必须是 "frontend-card-v1"',
    '- cards 数量必须是 4 到 8 张',
    '- 第一张卡片的 type 必须是 "cover"',
    '- 最后一张卡片的 type 必须是 "summary"',
    '- 中间所有卡片的 type 都必须是 "bullet"',
    '- cover 卡片必须包含英文键名：id、type、title、subtitle、tag',
    '- cover 的 tag 必须是 "前端知识点"',
    '- cover 的 title 最多 24 个中文字符',
    '- cover 的 subtitle 最多 40 个中文字符',
    '- bullet 卡片必须包含英文键名：id、type、title、bullets',
    '- bullet 的 title 最多 22 个中文字符',
    '- bullets 数量必须是 2 到 4 条',
    '- 每条 bullet 最多 30 个中文字符',
    '- summary 卡片必须包含英文键名：id、type、title、summary、cta',
    '- summary 的 title 最多 22 个中文字符',
    '- summary 的 summary 最多 80 个中文字符',
    '- summary 的 cta 最多 24 个中文字符',
    '- 任意字段中都不能出现 HTML、Markdown、emoji 或代码块',
    '',
    `目标知识点：${topic}`,
    '',
    '讲解草稿：',
    stage1Draft,
  ].join('\n');
}

export function buildStage2RetryPrompt(
  topic: string,
  stage1Draft: string,
  previousOutput: string,
  validationError: string
): string {
  return [
    '你上一次输出的 JSON 不合格，请立即重写为合法 JSON。',
    '只输出 JSON，不要解释，不要 Markdown 代码块。',
    '所有对用户可见的内容都必须使用简体中文。',
    '内容必须严格围绕指定知识点。',
    '',
    `目标知识点：${topic}`,
    '',
    '校验错误：',
    validationError,
    '',
    '上一版输出：',
    previousOutput || '（空）',
    '',
    '讲解草稿：',
    stage1Draft,
  ].join('\n');
}

export function buildRepairPrompt(
  topic: string,
  stage1Draft: string,
  invalidStage2: string,
  validationErrors: string
): string {
  return [
    '请修复下面这个 JSON 文档，使它完全满足要求的结构和内容限制。',
    '只输出 JSON 对象，不要 Markdown，不要解释。',
    '保留原本的教学价值，且所有可见内容都必须使用简体中文。',
    '主题必须严格保持与指定知识点一致。',
    '结果要清晰、专业、实用、细节到位，并且让前端读者觉得值得收藏。',
    '',
    `目标知识点：${topic}`,
    '',
    '原始讲解草稿：',
    stage1Draft,
    '',
    '校验错误：',
    validationErrors,
    '',
    '待修复的 JSON 或非法文档：',
    invalidStage2,
    '',
    '必须满足的约束：',
    '- styleVersion 必须等于 "frontend-card-v1"',
    '- cards 数量必须是 4 到 8 张',
    '- 第一张必须是 cover，最后一张必须是 summary，中间只能是 bullet',
    '- cover.tag 必须等于 "前端知识点"',
    '- cover.title 最多 24 个中文字符',
    '- cover.subtitle 最多 40 个中文字符',
    '- bullet.title 最多 22 个中文字符',
    '- 每张 bullet 卡片必须有 2 到 4 条 bullet',
    '- 每条 bullet 最多 30 个中文字符',
    '- summary.title 最多 22 个中文字符',
    '- summary.summary 最多 80 个中文字符',
    '- summary.cta 最多 24 个中文字符',
    '- 不能出现 HTML、Markdown、emoji 或代码块',
  ].join('\n');
}
